// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProduccionBack.Models;

public partial class EquipoContext : DbContext
{
    public EquipoContext(DbContextOptions<EquipoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Equipo> Equipos { get; set; }

    public virtual DbSet<Jugador> Jugadores { get; set; }

    public virtual DbSet<Persona> Personas { get; set; }

    public virtual DbSet<Posicion> Posiciones { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Equipo>(entity =>
        {
            entity.HasKey(e => e.IdEquipo).HasName("PK__Equipos__EE01F88A1D7E13C8");

            entity.Property(e => e.IdEquipo)
                .ValueGeneratedNever()
                .HasColumnName("id_equipo");
            entity.Property(e => e.DirectorTecnico).HasColumnName("director_tecnico");
            entity.Property(e => e.NombreEquipo)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("nombre_equipo");

            entity.HasOne(d => d.DirectorTecnicoNavigation).WithMany(p => p.Equipos)
                .HasForeignKey(d => d.DirectorTecnico)
                .HasConstraintName("fk_director_tecnico");
        });

        modelBuilder.Entity<Jugador>(entity =>
        {
            entity.HasKey(e => e.IdJugador).HasName("PK__Jugadore__75BB83E2372530C0");

            entity.Property(e => e.IdJugador)
                .ValueGeneratedNever()
                .HasColumnName("id_jugador");
            entity.Property(e => e.IdEquipo).HasColumnName("id_equipo");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.IdPosicion).HasColumnName("id_posicion");
            entity.Property(e => e.NroCamiseta).HasColumnName("nro_camiseta");

            entity.HasOne(d => d.IdEquipoNavigation).WithMany(p => p.Jugadores)
                .HasForeignKey(d => d.IdEquipo)
                .HasConstraintName("fk_equipo");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.Jugadores)
                .HasForeignKey(d => d.IdPersona)
                .HasConstraintName("fk_persona");

            entity.HasOne(d => d.IdPosicionNavigation).WithMany(p => p.Jugadores)
                .HasForeignKey(d => d.IdPosicion)
                .HasConstraintName("fk_posicion");
        });

        modelBuilder.Entity<Persona>(entity =>
        {
            entity.HasKey(e => e.IdPersona).HasName("PK__Personas__228148B00D87E45A");

            entity.Property(e => e.IdPersona)
                .ValueGeneratedNever()
                .HasColumnName("id_persona");
            entity.Property(e => e.Dni).HasColumnName("dni");
            entity.Property(e => e.FechaNac).HasColumnName("fecha_nac");
            entity.Property(e => e.NombreCompleto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre_completo");
        });

        modelBuilder.Entity<Posicion>(entity =>
        {
            entity.HasKey(e => e.IdPosicion).HasName("PK__Posicion__2234F8105D576EBB");

            entity.Property(e => e.IdPosicion).HasColumnName("id_posicion");
            entity.Property(e => e.Posicion)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("posicion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}