// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ProduccionBack.Models;

public partial class EquiposLigasInfo
{
    public int IdEquipoLigaInfo { get; set; }

    public int IdEquipo { get; set; }

    public short? PartidosG { get; set; }

    public short? PartidosP { get; set; }

    public decimal? Puntuacion { get; set; }

    public bool Alta { get; set; }

    [JsonIgnore]
    public virtual Equipos IdEquipoNavigation { get; set; }
}