// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProduccionBack.Models;

public partial class JugadoresLog
{
    public int IdJugadorLog { get; set; }

    public int IdJugador { get; set; }

    public short NroCamiseta { get; set; }

    public int IdPosicion { get; set; }

    public int IdEquipo { get; set; }

    public DateOnly FechaActualizacion { get; set; }

    public virtual Equipos IdEquipoNavigation { get; set; }

    public virtual Jugadores IdJugadorNavigation { get; set; }

    public virtual Posiciones IdPosicionNavigation { get; set; }
}