// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProduccionBack.Models;

public partial class Jugadores
{
    public int IdJugador { get; set; }

    public int IdPersona { get; set; }

    public short NroCamiseta { get; set; }

    public int IdPosicion { get; set; }

    public int IdEquipo { get; set; }

    public bool Alta { get; set; }

    public virtual Equipos IdEquipoNavigation { get; set; }

    public virtual Personas IdPersonaNavigation { get; set; }

    public virtual Posiciones IdPosicionNavigation { get; set; }

    public virtual ICollection<JugadoresLog> JugadoresLogs { get; set; } = new List<JugadoresLog>();
}