// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProduccionBack.Models;

public partial class Jugador
{
    public int IdJugador { get; set; }

    public int? IdPersona { get; set; }

    public int? NroCamiseta { get; set; }

    public int? IdPosicion { get; set; }

    public int? IdEquipo { get; set; }

    public virtual Equipo IdEquipoNavigation { get; set; }

    public virtual Persona IdPersonaNavigation { get; set; }

    public virtual Posicion IdPosicionNavigation { get; set; }
}