// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ProduccionBack.Models;

public partial class Ligas
{
    public int IdLiga { get; set; }

    public string Liga1 { get; set; }

    public bool Alta { get; set; }
    [JsonIgnore]
    public virtual ICollection<Equipos> Equipos { get; set; } = new List<Equipos>();
}