// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProduccionBack.Models;

public partial class Partidos
{
    public int IdPartido { get; set; }

    public int IdLocal { get; set; }

    public int IdVisitante { get; set; }

    public DateOnly FechaPartido { get; set; }

    public TimeOnly HoraPartido { get; set; }

    public int Arbitro { get; set; }

    public int? ResultadoLocal { get; set; }

    public int? ResultadoVisitante { get; set; }

    public virtual Personas ArbitroNavigation { get; set; }

    public virtual Equipos IdLocalNavigation { get; set; }

    public virtual Equipos IdVisitanteNavigation { get; set; }
}