// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProduccionBack.Models;

public partial class Personas
{
    public int IdPersona { get; set; }

    public string NombreCompleto { get; set; }

    public int Dni { get; set; }

    public DateOnly FechaNac { get; set; }

    public bool Alta { get; set; }

    public virtual ICollection<Equipos> Equipos { get; set; } = new List<Equipos>();

    public virtual ICollection<Jugadores> Jugadores { get; set; } = new List<Jugadores>();

    public virtual ICollection<Partidos> Partidos { get; set; } = new List<Partidos>();
}