// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProduccionBack.Models;

public partial class Persona
{
    public int IdPersona { get; set; }

    public string NombreCompleto { get; set; }

    public int? Dni { get; set; }

    public DateOnly? FechaNac { get; set; }

    public virtual ICollection<Equipo> Equipos { get; set; } = new List<Equipo>();

    public virtual ICollection<Jugador> Jugadores { get; set; } = new List<Jugador>();
}